name: pennyworth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - requests>=2.32.3
  - pytz>=2024.1
  - python-dotenv>=1.0.1
  - tenacity>=8.2.3
  - google-auth>=2.36.0
  - pip
  - pip:
    - slack_bolt>=1.22.0
    - slack_sdk>=3.34.0
    - google-generativeai>=0.8.4
    - py-trello>=0.20.0
    - schedule>=1.2.2
    - datetime-utils>=0.2.0
    - google-api-python-client>=2.154.0