[tool.semantic_release]
version_variables = ["src/__init__.py:__version__"]
branch = "main"
upload_to_pypi = false
upload_to_repository = true
build_command = ""
commit_version_number = true
github_token = GH_TOKEN